<?php

if (!defined('AOWOW_REVISION'))
    die('illegal access');


// menuId 5: Profiler g_initPath()
//  tabId 1: Tools    g_initHeader()
class SignaturePage extends GenericPage
{
    protected $path     = [1, 5];
    protected $tabId    = 1;
    protected $tpl      = 'signature';
    protected $gDataKey = true;
    protected $scripts  = array(
        [SC_CSS_FILE, 'css/Profiler.css']
    );

    private   $profileId   = 0;
    protected $profileData = null;

    protected $_get = array(
        'profile' => ['filter' => FILTER_CALLBACK, 'options' => 'GenericPage::checkTextLine']
    );

    public function __construct($pageCall, $pageParam)
    {
        parent::__construct($pageCall, $pageParam);

        if (!Cfg::get('PROFILER_ENABLE'))
            $this->error();

        $profileParam = $this->_get['profile'] ?? '';
        if (!$profileParam)
            $this->error();

        // Try numeric ID first
        if (is_numeric($profileParam))
        {
            $this->profileId = intval($profileParam);
        }
        else
        {
            // Try region.realm.name format
            $parts = explode('.', $profileParam);
            if (count($parts) == 3)
            {
                $realm = Profiler::urlize($parts[1], true);
                $name  = Profiler::urlize($parts[2]);

                // Look up realm
                $realmId = 0;
                foreach (Profiler::getRealms() as $rId => $rData)
                {
                    if (Profiler::urlize($rData['name'], true) == $realm)
                    {
                        $realmId = $rId;
                        break;
                    }
                }

                if ($realmId)
                {
                    $id = DB::Aowow()->selectCell(
                        'SELECT id FROM ?_profiler_profiles WHERE realm = ?d AND name = ?',
                        $realmId, Util::ucFirst($name)
                    );
                    if ($id)
                        $this->profileId = $id;
                }
            }
        }

        if (!$this->profileId)
            $this->error();

        // Load profile data
        $this->profileData = DB::Aowow()->selectRow(
            'SELECT p.id, p.name, p.level, p.class, p.race, p.gender, p.realm, p.guild,
                    pg.name AS guildname
             FROM   ?_profiler_profiles p
             LEFT JOIN ?_profiler_guild pg ON pg.id = p.guild
             WHERE  p.id = ?d',
            $this->profileId
        );

        if (!$this->profileData)
            $this->error();

        // Look up realm name from auth DB
        $this->profileData['realmname'] = '';
        if ($this->profileData['realm'])
        {
            foreach (Profiler::getRealms() as $rId => $rData)
            {
                if ($rId == $this->profileData['realm'])
                {
                    $this->profileData['realmname'] = $rData['name'];
                    break;
                }
            }
        }

        $this->name = 'Signature';
    }

    protected function generateContent()
    {
        // Page content is generated by the template
    }

    protected function generateTitle()
    {
        $name = $this->profileData['name'] ?? 'Character';
        array_unshift($this->title, $name, 'Signature');
    }

    protected function generatePath() {}
}

?>
